from __future__ import annotations

import json
import os
from dataclasses import asdict, is_dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI


load_dotenv()


DEFAULT_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

PROMPT_DIR = Path(__file__).parent / "prompts"

ENHANCE_PROMPT_PATH = PROMPT_DIR / "root_cause_enhance_prompt.txt"


class LLMClientError(Exception):
    """Error raised by Root-Cause LLM client."""


def _json_safe(obj: Any) -> Any:
    """
    Convert Python objects into JSON-safe data.

    Supports:
    - dataclass
    - enum
    - dict
    - list
    - primitive values
    """

    if obj is None:
        return None

    if isinstance(obj, Enum):
        return obj.value

    if is_dataclass(obj):
        return _json_safe(asdict(obj))

    if isinstance(obj, dict):
        return {str(key): _json_safe(value) for key, value in obj.items()}

    if isinstance(obj, list):
        return [_json_safe(item) for item in obj]

    return obj


def _load_prompt_template(prompt_path: Path) -> str:
    """
    Load prompt template from local txt file.
    """

    if not prompt_path.exists():
        raise LLMClientError(f"Prompt file not found: {prompt_path}")

    return prompt_path.read_text(encoding="utf-8")


def _build_prompt_from_template(
    *,
    prompt_path: Path,
    payload: dict[str, Any],
) -> str:
    """
    Load prompt template and insert runtime JSON payload.

    The txt file must contain this placeholder:

        {{payload}}

    Example:
        Input:
        {{payload}}
    """

    template = _load_prompt_template(prompt_path)

    payload_json = json.dumps(
        payload,
        ensure_ascii=False,
        indent=2,
    )

    return template.replace("{{payload}}", payload_json)


class RootCauseLLMClient:
    """
    OpenAI client for Root-Cause Agent.

    This class only handles:
    1. Loading prompt template from txt.
    2. Injecting JSON payload into the template.
    3. Calling OpenAI.
    4. Parsing and normalizing the JSON response.

    It should NOT:
    - Detect discrepancies.
    - Recalculate amounts.
    - Decide audit status.
    - Override rule-based results.
    """

    def __init__(self, model: str = DEFAULT_MODEL):
        api_key = os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise LLMClientError(
                "Missing OPENAI_API_KEY. "
                "Please add it to your local .env file."
            )

        self.model = model
        self.client = OpenAI(api_key=api_key)

    def enhance_analysis(
        self,
        *,
        discrepancy: Any,
        rule_analysis: Any,
        matched: Any | None = None,
        entity_consistency: Any | None = None,
        trace_id: str = "",
    ) -> dict[str, Any]:
        """
        Enhance a rule-based AnomalyAnalysis.

        This method is designed to work with the enhancer layer.

        Input:
        - discrepancy: one Discrepancy from ReconciliationOutput
        - rule_analysis: one AnomalyAnalysis generated by rule engine
        - matched: matched fields from ReconciliationOutput
        - entity_consistency: entity consistency result
        - trace_id: trace id for debugging

        Output:
        {
            "explanation": str,
            "alternative_causes": list[dict],
            "recommended_action": str
        }

        Important:
        The LLM is not allowed to change:
        - probable_cause
        - status
        - risk_level
        - requires_human
        - confidence
        """

        payload = {
            "trace_id": trace_id,
            "discrepancy": _json_safe(discrepancy),
            "rule_analysis": _json_safe(rule_analysis),
            "matched": _json_safe(matched),
            "entity_consistency": _json_safe(entity_consistency),
        }

        prompt = _build_prompt_from_template(
            prompt_path=ENHANCE_PROMPT_PATH,
            payload=payload,
        )

        raw_result = self._call_openai_json(prompt)

        return self._normalize_enhancement_result(raw_result)

    def _call_openai_json(self, prompt: str) -> dict[str, Any]:
        """
        Call OpenAI and require a JSON object response.
        """

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                temperature=0.1,
                response_format={"type": "json_object"},
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a strict financial audit root-cause assistant. "
                            "Return valid JSON only. "
                            "Do not invent facts."
                        ),
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    },
                ],
            )
        except Exception as exc:
            raise LLMClientError(f"OpenAI API call failed: {exc}") from exc

        content = response.choices[0].message.content

        if not content:
            raise LLMClientError("OpenAI returned empty response.")

        try:
            result = json.loads(content)
        except json.JSONDecodeError as exc:
            raise LLMClientError(
                f"OpenAI returned invalid JSON: {content}"
            ) from exc

        if not isinstance(result, dict):
            raise LLMClientError(
                f"OpenAI returned non-object JSON: {content}"
            )

        return result

    def _normalize_enhancement_result(
        self,
        result: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Normalize LLM enhancement result.

        The enhancer only accepts:
        - explanation
        - alternative_causes
        - recommended_action

        Any other fields returned by the LLM are ignored.
        """

        explanation = result.get("explanation", "")
        recommended_action = result.get("recommended_action", "")
        alternative_causes = result.get("alternative_causes", [])

        if not isinstance(explanation, str):
            explanation = ""

        if not isinstance(recommended_action, str):
            recommended_action = ""

        if not isinstance(alternative_causes, list):
            alternative_causes = []

        cleaned_alternative_causes: list[dict[str, Any]] = []

        for item in alternative_causes:
            if not isinstance(item, dict):
                continue

            cause = item.get("cause", "")
            confidence = item.get("confidence", 0.5)

            if not isinstance(cause, str) or not cause.strip():
                continue

            try:
                confidence = float(confidence)
            except (TypeError, ValueError):
                confidence = 0.5

            confidence = max(0.0, min(1.0, confidence))

            cleaned_alternative_causes.append(
                {
                    "cause": cause.strip(),
                    "confidence": confidence,
                }
            )

        return {
            "explanation": explanation.strip(),
            "alternative_causes": cleaned_alternative_causes,
            "recommended_action": recommended_action.strip(),
        }